version: '3'

services:
  gif_search_index:
    build:
      context: gif_search_index
    env_file:
      - .env

  gif_search_api:
    build:
      context: gif_search_api
    env_file:
      - .env
    depends_on:
      - gif_search_index
    ports:
      - "8000:8000"

  gif_search_frontend:
    build:
      context: gif_search_frontend
    env_file:
      - .env
    depends_on:
      - gif_search_api
    ports:
      - "8501:8501"