[project]
name = "gif_search_api"
version = "0.1"
dependencies = [
    "numpy==1.26.2",
    "pinecone-client==3.1.0",
    "pandas",
    "tqdm",
    "sentence-transformers"
]

[project.optional-dependencies]
dev = ["black", "flake8"]